/**
 * ════════════════════════════════════════════════════════════
 *  AVON_BOT ALERT — Velocity Directive VD-2026-02-27-001
 *  Generated by: Gemini (Lead Architect)
 *  Timestamp:    2026-02-27T12:57:40-05:00
 *
 *  STATUS: 🔴 LIVE — A new directive is active. Swarm standing by.
 * ════════════════════════════════════════════════════════════
 *
 *  This file is read by Avon_Bot on each startup cycle.
 *  It broadcasts the active directive to all registered agents
 *  and routes sub-tasks to the appropriate execution lane.
 *
 *  Routing Logic:
 *    Logic / Security / Complex API  → DeepSeek
 *    UI / Components / Boilerplate   → Local CodeGemma
 *    File I/O & Merging              → Local Llama/Phi-4
 *    Final Review / Validation       → Gemini (Lead)
 * ════════════════════════════════════════════════════════════
 */

import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');

const DIRECTIVE_PATH = path.join(PROJECT_ROOT, 'swarm', 'directives', 'VD-2026-02-27-001.json');
const ALERT_LOG_PATH = path.join(PROJECT_ROOT, 'memory', 'swarm_alerts.jsonl');

// ─── Lane → Agent Map ─────────────────────────────────────────
const AGENT_ROUTER = {
    'Logic/Security/Complex API': 'DeepSeek',
    'UI/Components/Boilerplate': 'CodeGemma',
    'File I/O & Merging': 'Llama/Phi-4',
};

/**
 * broadcastDirective()
 * Reads the active directive JSON and emits task assignments
 * to each agent lane. Called by Avon_Bot on boot or poll.
 */
export async function broadcastDirective() {
    console.log('\n╔══════════════════════════════════════════════════════╗');
    console.log('║   AVON_BOT — VELOCITY DIRECTIVE ALERT               ║');
    console.log('╚══════════════════════════════════════════════════════╝\n');

    const directive = await fs.readJson(DIRECTIVE_PATH).catch(err => {
        console.error('[Alert] ❌ Could not read directive file:', err.message);
        return null;
    });

    if (!directive) return;

    console.log(`[Alert] 📡 Directive ID     : ${directive.directive_id}`);
    console.log(`[Alert] 🕐 Timestamp        : ${directive.timestamp}`);
    console.log(`[Alert] 📊 Status           : ${directive.status}`);
    console.log(`[Alert] 📋 Blueprint        : ${directive.blueprint_ref}`);
    console.log(`[Alert] 🗺️  Priority Order   : ${directive.priority_order.join(' → ')}`);
    console.log('\n[Alert] 🔀 ROUTING ASSIGNMENTS:\n');

    const tasksByAgent = {};
    for (const [taskId, task] of Object.entries(directive.tasks)) {
        const agent = task.agent;
        if (!tasksByAgent[agent]) tasksByAgent[agent] = [];
        tasksByAgent[agent].push(task);
    }

    for (const [agent, tasks] of Object.entries(tasksByAgent)) {
        console.log(`  ▶ ${agent.toUpperCase()}:`);
        for (const task of tasks) {
            const icon = task.priority === 'critical' ? '🔴' : task.priority === 'high' ? '🟠' : '🟡';
            console.log(`    ${icon} [${task.id}] ${task.title}`);
            console.log(`        └─ Files: ${task.target_files.join(', ')}`);
        }
        console.log('');
    }

    // ─── Log the alert broadcast ───────────────────────────────
    const alertEntry = {
        timestamp: new Date().toISOString(),
        directive_id: directive.directive_id,
        type: 'BROADCAST',
        agents_alerted: Object.keys(tasksByAgent),
        task_count: Object.keys(directive.tasks).length,
        status: directive.status,
    };

    await fs.ensureFile(ALERT_LOG_PATH);
    await fs.appendFile(ALERT_LOG_PATH, JSON.stringify(alertEntry) + '\n');

    console.log(`[Alert] ✅ Broadcast logged to: memory/swarm_alerts.jsonl`);
    console.log('[Alert] 🚀 Swarm is standing by. Execute directives in priority order.\n');

    return tasksByAgent;
}

/**
 * markTaskComplete(taskId, result)
 * Called by individual agents when they complete their assigned task.
 * Updates the directive JSON with status and logs the completion.
 */
export async function markTaskComplete(taskId, result = {}) {
    const directive = await fs.readJson(DIRECTIVE_PATH);
    if (!directive.tasks[taskId]) {
        console.warn(`[Alert] ⚠️  Unknown task ID: ${taskId}`);
        return;
    }

    directive.tasks[taskId].status = 'complete';
    directive.tasks[taskId].completed_at = new Date().toISOString();
    directive.tasks[taskId].result = result;

    await fs.writeJson(DIRECTIVE_PATH, directive, { spaces: 2 });

    const allComplete = Object.values(directive.tasks).every(t => t.status === 'complete');
    if (allComplete) {
        directive.status = 'COMPLETE — PENDING_GEMINI_REVIEW';
        await fs.writeJson(DIRECTIVE_PATH, directive, { spaces: 2 });
        console.log('\n[Alert] 🏁 ALL TASKS COMPLETE — Flagging for Gemini Final Review.\n');
    }

    const logEntry = {
        timestamp: new Date().toISOString(),
        directive_id: directive.directive_id,
        type: 'TASK_COMPLETE',
        task_id: taskId,
        agent: directive.tasks[taskId].agent,
        result,
    };
    await fs.ensureFile(ALERT_LOG_PATH);
    await fs.appendFile(ALERT_LOG_PATH, JSON.stringify(logEntry) + '\n');

    console.log(`[Alert] ✅ Task ${taskId} marked complete.`);
}

/**
 * getDirectiveStatus()
 * Returns the current status of the active directive (pending/complete counts).
 */
export async function getDirectiveStatus() {
    const directive = await fs.readJson(DIRECTIVE_PATH);
    const tasks = Object.values(directive.tasks);
    const pending = tasks.filter(t => t.status === 'pending').length;
    const complete = tasks.filter(t => t.status === 'complete').length;

    return {
        directive_id: directive.directive_id,
        status: directive.status,
        total: tasks.length,
        pending,
        complete,
        pct_complete: Math.round((complete / tasks.length) * 100),
    };
}

// ─── Auto-broadcast on direct execution ───────────────────────
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
    broadcastDirective().catch(console.error);
}
