-- Listings Database Schema for Supabase
-- Auto-generated by Avon Template Injection System

CREATE TABLE IF NOT EXISTS listings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  price NUMERIC(12, 2) NOT NULL,
  address TEXT NOT NULL,
  beds INTEGER NOT NULL DEFAULT 0,
  baths NUMERIC(3, 1) NOT NULL DEFAULT 0,
  sqft INTEGER,
  type TEXT CHECK (type IN ('Condo', 'Single Family', 'Townhouse', 'Penthouse', 'Multi-Family')),
  image_url TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  description TEXT,
  agent_name TEXT,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Under Contract', 'Sold', 'Off Market')),
  year_built INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public can view active listings"
  ON listings FOR SELECT
  USING (status = 'Active');

-- Authenticated users can insert
CREATE POLICY "Authenticated users can insert listings"
  ON listings FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Owners can update their listings
CREATE POLICY "Users can update own listings"
  ON listings FOR UPDATE
  TO authenticated
  USING (agent_name = current_setting('request.jwt.claims')::json->>'name');

-- Seed data
INSERT INTO listings (title, price, address, beds, baths, sqft, type, lat, lng, description, agent_name, status, year_built) VALUES
  ('Modern Loft in Arts District', 750000, '421 N Spring St, Los Angeles, CA 90012', 2, 2, 1850, 'Condo', 34.0565, -118.2380, 'Sun-drenched industrial loft with 16ft ceilings.', 'Sarah Chen', 'Active', 2019),
  ('Craftsman Bungalow with Pool', 1250000, '1847 Oak Glen Dr, Pasadena, CA 91104', 4, 3, 2800, 'Single Family', 34.1678, -118.1445, 'Beautifully restored 1920s craftsman.', 'Marcus Rivera', 'Active', 1924),
  ('Beachfront Studio', 425000, '2200 Ocean Front Walk, Venice, CA 90291', 1, 1, 650, 'Condo', 33.9850, -118.4695, 'Steps from the sand with ocean views.', 'Sarah Chen', 'Active', 2015),
  ('Hillside Contemporary Villa', 3200000, '8901 Mulholland Dr, Los Angeles, CA 90046', 5, 6, 5200, 'Single Family', 34.1283, -118.3681, 'Architectural masterpiece with infinity pool.', 'James Park', 'Active', 2022),
  ('Downtown Penthouse', 1875000, '900 W Olympic Blvd PH3, Los Angeles, CA 90015', 3, 3, 3100, 'Penthouse', 34.0432, -118.2665, 'Full-floor penthouse with wraparound terrace.', 'Marcus Rivera', 'Under Contract', 2021),
  ('Cozy Townhome near Metro', 595000, '3344 Figueroa St, Los Angeles, CA 90007', 2, 2.5, 1400, 'Townhouse', 34.0224, -118.2787, 'Move-in ready townhome with rooftop deck.', 'James Park', 'Active', 2020);
